openapi: 3.0.3
info:
  title: Petstore GET Demo
  version: 1.0.0
servers:
  - url: https://petstore3.swagger.io/api/v3
paths:
  /pet/{petId}:
    get:
      summary: Get pet by ID
      parameters:
        - in: path
          name: petId
          required: true
          schema: { type: integer }
      responses:
        "200": { description: OK }
